//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantMonitoringSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class node
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public node()
        {
            this.sensors = new HashSet<sensor>();
        }
    
        public int id { get; set; }
        public string physical_address { get; set; }
        public string friendly_name { get; set; }
        public int behavior_id { get; set; }
        public Nullable<bool> water_on { get; set; }
        public Nullable<bool> light_on { get; set; }
    
        public virtual behavior behavior { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sensor> sensors { get; set; }
    }
}
