//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantMonitoringSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class sensor
    {
        public sensor()
        {
            this.sensorreadings = new HashSet<sensorreading>();
        }
    
        public int id { get; set; }
        public string sensor_name { get; set; }
        public string measurement_name { get; set; }
        public string measurement_unit { get; set; }
        public int node_id { get; set; }
        public string friendly_name { get; set; }
    
        public virtual node node { get; set; }
        public virtual ICollection<sensorreading> sensorreadings { get; set; }
    }
}
